### PR TITLE
add ac edit page for front matter

### PR DESCRIPTION
**Pull request by j2kan**
made front matter editable for the ac.

decided to go with a txt file instead of a database entry implementation (from class).

will need to run `python manage.py collectstatic` after merging with master to have it work on the server and on your local!

thoroughly tested it locally.

if code review passes, i will test branch on the server.

### CODE REVIEW

**Review by amyleblond — DISMISSED** [review]
looks great! 
was able to follow based on the similarity with the course_upload.csv.

learned something from {% url 'home' %} -> understand why we name the urls now!

 In prod - reminder we had that path error with the course_upload.csv when it went to production, but path makes sense!

**Comment by lauradobson** [comment]
On the successful submission, can we link the application form directly for preview instead of "preview by clicking home and then step 3."?

I tested all fields though to make sure it updates - looks good.

I tried to add a CSV to see what happens when I add a different file type without the extension .txt and I got a success message "New front matter uploaded, preview by clicking home and then step 3."

The front matter then became the contents of the csv. We should add error protection to make sure only .txt can be uploaded
screen shot 2018-01-23 at 8 03 30 pm

**Comment by j2kan** [comment]
The linking to the application form directly to preview will make sense when we have an AC view of the application form for making it live etc... Since there's no back button on the application page I did not want it to just go there.

Added check for txt file extension.

**Review by amyleblond — APPROVED** [review]
nice!

**Comment by lauradobson** [comment]
tested multiple document types (csv, doc, jpg, pdf) and nothing uploaded! good to go

**Pull request merged**
