### PR TITLE
Symposium Poster

### PR DESCRIPTION
**Pull request by smwatts**
Appreciate your feedback!

### CODE REVIEW

**Review by lauradobson — CHANGES_REQUESTED** [review]
LOVE THE LAYOUT AND DESIGN

a few comments/reviews:

1. Font change request. If you look at the references in the other powerpoint on dropbox, none of them use a font similar to this. Personally I think it looks old school and would make me less drawn to our board over others.
2. 
image

image

Are these happening just on my download?
3. Create a section for testimonials and include two more that we've received....For sure Duimering's and say "-Former MSCI AC"
Let's force one out of smucker this week lol
4. For approach, step 8. I would change it to "TA Assignment Formulation & System Integration"
5. I think we need more visuals. Perhaps a graph or chart displaying the differences in the old vs new algorithm. It would REALLY emphasize that we are really adding value and have made a signifcant improvement
6. Maybe let's change the header colour from grey to a colour (like purple). I think it would help our board pop out more
7. Would change problem statement to this...creates a bit more space too 
image

**Comment by smwatts** [comment]
1. I was using Roboto because its the same font as our website, @j2kan and @amyleblond what do you think re: font?
2. I think that is just on your download, weird looking
3. (see 7)
4. Let me know if my latest commit is what you meant.
5. I thought about the visuals too but because the algorithm only adds 1 student each term (lol) I'm having a hard time coming up with something. @j2kan, @amyleblond let me know if you have ideas for this.
6. This is what purple would look like:
screen shot 2018-03-05 at 6 31 30 pm
- I liked the different colour title because I thought it would bring the colour scheme together, but agree it should be more bold. @j2kan and @amyleblond do you think the purple is better? (including purple in my lasted commit)
7. I kept the problem more spacey because the approach section isn't that long lol. We can try a version with Testimonial under Approach and see how that looks, I'll do that now for comparison.

**Comment by amyleblond** [comment]
Did you download Roboto font? Mine just shows as Times New Roman

**Comment by lauradobson** [comment]
Also I recommend dropping the "objectives" section to make room for more graphics. I think the current poster is a lot of text

**Pull request closed without merging**
