### PR TITLE
update email to envio

### PR DESCRIPTION
**Pull request by j2kan**
just update to pull from config file

### CODE REVIEW

**Review by amyleblond — APPROVED** [review]
This why email were coming from j2kan?

**Comment by smwatts** [comment]
@j2kan won't merge until we figure out "reply to"

**Comment by j2kan** [comment]
do not merge yet. will have to fix smuckers reply to thing.

**Comment by j2kan** [comment]
@amyleblond yes ideally email will just come from whatever is set in the environment file

**Comment by j2kan** [comment]
screen shot 2018-03-08 at 9 54 10 pm

I will update the server's enviro file.

**Comment by j2kan** [comment]
Reply screenshot showing it works 💃

**Review by smwatts — APPROVED** [review]
LGTM

**Comment by amyleblond** [comment]
screen shot 2018-03-08 at 10 23 53 pm
tried to send an email to myself --

**Pull request merged**
