### PR TITLE
50 students, 19 courses, 113 apps

### PR DESCRIPTION
**Pull request by amyleblond**
courses are what is actually offered in Spring 2018 term (links will work to waterloo api)
instructor emails are to ourselves
didn't do resumes, we can apply ourselves if we want that example
Each of the courses has at min 3 applicants, max 8ish
about half preferences filled in

### CODE REVIEW

**Comment by amyleblond** [comment]
[Dummy Data.xlsx](https://github.com/j2kan/ta-works/files/1765297/Dummy.Data.xlsx)

**Comment by amyleblond** [comment]
I put resumes on the Canadian students, rotate through the 4 of our resumes. This will only work on the server as the link is referencing students table -- THEREFORE, DONT WIPE STUDENTS TABLE ON SERVER!!!
 
:)

@smwatts @j2kan @lauradobson

**Review by j2kan — APPROVED** [review]
LGTM!!

NOTE: @lauradobson  @smwatts  @amyleblond  user terminal and not iterminal for copying and pasting this script.

**Comment by amyleblond** [comment]
the course with no rankings will be (max courseid - 18)

**Comment by amyleblond** [comment]
TEEHHEHE 
now: 950 apps (takes about 20 seconds)
SELCUK'S CLASS STILL IS LEFT EMPTY TO BE RANKED

**Review by lauradobson — APPROVED** [review]
good job amy!

**Pull request merged**
