### PR TITLE
visa expiry date will not disappear on page refresh if selected

### PR DESCRIPTION
**Pull request by amyleblond**
making sure that the student visa expiry date doesnt disappear on page refresh. new function added to onload that will trigger the no back and check for visa.

Still looking into reason button dissappearing

screen shot 2018-03-08 at 2 44 06 pm

### CODE REVIEW

**Comment by amyleblond** [comment]
reason button stays if you had an error on course submit :) 

screen shot 2018-03-08 at 7 43 28 pm

**Comment by smwatts** [comment]
LGTM!! 

Side note: When we merge your other PR that fixes the display issue for the # of courses applied to lets check to make sure this bug doesn't happen (where it says I didn't rank any courses).

screen shot 2018-03-08 at 9 24 24 pm
screen shot 2018-03-08 at 9 29 24 pm

**Comment by amyleblond** [comment]
@smwatts will be good! will be good!

**Comment by j2kan** [comment]
Nice, clean and simple solution.
Thanks for taking it.

**Review by j2kan — APPROVED** [review]
LGTM

**Pull request merged**
