### PR TITLE
fix refresh bug

### PR DESCRIPTION
**Pull request by j2kan**
easy money

### CODE REVIEW

**Comment by j2kan** [comment]
@amyleblond @smwatts I TOLD U we could of combined this to the other tiket

**Review by smwatts — COMMENTED** [review]
Lmao okay

**Review by amyleblond — DISMISSED** [review]
ticket for 2 minutes?

**Comment by j2kan** [comment]
This should work on safari now too if they press back, the ratings will persist.

**Review by smwatts — APPROVED** [review]
thanks for adding this! I think all the refresh issues are solved with this PR. When we do "find the bugs" we should double check though!

**Comment by amyleblond** [comment]
good addition @smwatts , looks good @j2kan !

**Pull request merged**
