### PR TITLE
char limit & application close message

### PR DESCRIPTION
**Pull request by smwatts**
Before running you will have to run migrate on the models & collect static files

I fixed the size of the box, it accepts 1500 chars
screen shot 2018-02-10 at 2 04 18 pm

Also added a couple messages to let users know that once you submit, you're done with the application page.
screen shot 2018-02-10 at 8 01 39 am
screen shot 2018-02-10 at 8 01 56 am

Finally, changed collectstatic"s" to collectstatic in the ReadMe.md

### CODE REVIEW

**Comment by amyleblond** [comment]
@smwatts did you extend the textbox yourself? Is that what the second screenshot is showing?

**Comment by smwatts** [comment]
yep I extended it @amyleblond !

**Comment by amyleblond** [comment]
so the question to @j2kan is asking how we can program it to be a bigger size? right? @smwatts just making sure I'm following

**Comment by smwatts** [comment]
Exactly! or if we are okay to leave it like this then we can merge - but probs better to fix it lol

**Comment by amyleblond** [comment]
agreed for fixing lol -- I changed the width of the preference drop down menu and it was in css under the class he created -- from my understanding of his demo, the pop up he had to manual create in the jquery file

**Comment by j2kan** [comment]
How come the pop up is bigger right now just from the max_length=1500 line change?

**Comment by j2kan** [comment]
inside app-jquery.js

 function btnClick(e){
    e.preventDefault();
    var currentContext = $(this).parent();
    // makes a temporary dialog for taking user input
    $('<div><p>(255 character limit)</p><textarea maxlength=255 id=tempBox ></textarea></div>').dialog({
      modal: true,
      height: 350,
      width: 330,
      resizable: false,
      draggable: false,
      closeOnEscape: false,
      title: "Enter your reason below.",
      buttons: {
        'OK': function () {
          currentContext.find('.reason_class').val($('#tempBox').val());
          $(this).dialog("destroy");
          $(this).remove();
        },
        'Cancel': function () {
          $(this).dialog("destroy");
          $(this).remove();
        }
      }
    });
    $('#tempBox').val(currentContext.find('.reason_class').val());
  };

^^height and width is where you want to play around with

**Comment by j2kan** [comment]
and inside style.css



textarea {
  width: 300px;
  height: 150px;
}


You want to mess with the above too!

**Comment by smwatts** [comment]
@j2kan & @amyleblond -> fixed thanks :)

**Review by j2kan — APPROVED** [review]
LGTM.

**Review by amyleblond — APPROVED** [review]
thanks for figuring that out :)

**Pull request merged**
