### PR TITLE
fix bug and display order

### PR DESCRIPTION
**Pull request by j2kan**
1. fixed bug of students not showing
2. changed filter logic to use inner join
3. Added naming instead of column filters
4. added empty course positions as part of algortihm export

### CODE REVIEW

**Comment by amyleblond** [comment]
@j2kan I had added the naming update thing to this ticket - no big deal if we leave it but I think changing the names to not appear like the field names would be good. I know @lauradobson did the TA Size from position type

**Comment by smwatts** [comment]
@j2kan  Merge Conflicts

**Comment by j2kan** [comment]
screen shot 2018-03-08 at 9 38 44 pm
screen shot 2018-03-08 at 9 38 50 pm
screen shot 2018-03-08 at 9 38 59 pm

**Comment by j2kan** [comment]
@amyleblond addressed the field naming
@smwatts addressed the export according to the PDF. it will be at the end of the file.

**Comment by smwatts** [comment]
If we have a duplicated student, they will not appear in the match results:

screen shot 2018-03-08 at 10 03 31 pm
screen shot 2018-03-08 at 10 03 21 pm

**Comment by j2kan** [comment]
WTF @smwatts bug queen strikes again

**Comment by amyleblond** [comment]
@smwatts how do you notice this lol smarty

**Comment by j2kan** [comment]
@smwatts great find. This will help battle the concept of duplicate students.

**Comment by lauradobson** [comment]
@smwatts woah awesome find sarah!

**Comment by j2kan** [comment]
@amyleblond @smwatts @lauradobson lots of conversations, not enough approvals.

**Comment by smwatts** [comment]
Please document the "known bug" of duplicate courses having the same effect. Then I'll merge spazy spazz

**Comment by smwatts** [comment]
@amyleblond & @lauradobson Johnson and me discussed the design decision of not coding for duplicate courses. Reasons are:
1. We have no way to show the user "course ID" from Django -> course are only shown from a form and because we are pulling from a form and not a model we don't have access to the ID
          Because of this it's not meaningful to include a unique identifier like course ID
2. We know that the courses are input by the AC, this provides higher data quality than applications which are input by students.

TO DO tomorrow: Discuss this design decision!!

**Comment by lauradobson** [comment]
@smwatts Could we potentially deal with this when courses are added in? Meaning, when it does the "Validation" step, we check for duplicates and if one is detected, we add "Course 1" and "Course 2" to the instructor name or something?

**Review by smwatts — APPROVED** [review]
LGTM

**Comment by j2kan** [comment]
We should prevent the AC from uploading and throw a error if those 3 things that make a course unique are duplicated.
Because he only gets 1 shot to upload, if there's duplicates it gives a bad experience for students applying too.

**Review by amyleblond — APPROVED** [review]

**Pull request merged**
