### PR TITLE
fix Ranking Status Page bug

### PR DESCRIPTION
**Pull request by amyleblond**
Reason this bug existed: we default instructor preferences to 0 -- this means that our avg rating function would never produce a 'None' rating. 

Changing the check to be if avg rating = 0, checks if any student has been ranked. 

Changes: 
**views.py**: tiny logic change
screen shot 2018-03-07 at 1 13 15 pm

### CODE REVIEW

**Comment by j2kan** [comment]
I don't think it should say NOT submitted anymore.

What if an instructor doesn't like any students and ranks them all a 0 anyways?

**Review by lauradobson — COMMENTED** [review]
Should we make more scenarios:

1. If AC marked all applied students to a course: No Applicants 
2. If the prof doesn't rank any students but still submits that: Did not select a TA

other than that it worked!

**Comment by smwatts** [comment]
I'd just change "NOT submitted" to "No students ranked" and not worry about other cases

**Comment by amyleblond** [comment]
screen shot 2018-03-07 at 5 39 09 pm

**Comment by smwatts** [comment]
Looks good Amy! In this test case I disqualified 2 / 3 students that applied to a course. I'd expect the number of apps for this course to be 1. Right now we aren't considering is_disqualified in the app count logic so the count = 2. Do we want this to be part of this ticket? Or make a new ticket for it?

And I think we should change the wording to "# of eligible apps" instead of "# of apps"

screen shot 2018-03-07 at 5 48 21 pm
screen shot 2018-03-07 at 5 48 38 pm

**Comment by amyleblond** [comment]
@smwatts - good catch. 
@j2kan readme updated for course upload here --- readme was done for ranking status earlier pr
code is a double yucky join but it works. See Bon Koo - disqulaified one student in his class
screen shot 2018-03-07 at 7 06 37 pm
screen shot 2018-03-07 at 7 07 35 pm

**Comment by amyleblond** [comment]
I meant to say selcuk & bon^ 
removed a student applied to multiple

**Comment by amyleblond** [comment]
and header change @smwatts 
screen shot 2018-03-07 at 7 13 30 pm

**Comment by smwatts** [comment]
Interesting new bug:

When you have all students disqualified, the course info page becomes:
screen shot 2018-03-08 at 8 56 33 pm

All students disqualified:
screen shot 2018-03-08 at 8 53 23 pm

Instead we would want to show all courses with "no apps"

**Comment by smwatts** [comment]
Did test a general case when we have a mix of qualified and disqualified students - works really well! Thanks for making that change

**Comment by amyleblond** [comment]
@smwatts ok should work now. screenshots of three different cases below: 
1. courses but no students/all disqualified students
screen shot 2018-03-08 at 9 28 59 pm
2. Courses & applicants
screen shot 2018-03-08 at 9 30 05 pm
3. no courses
screen shot 2018-03-08 at 9 31 36 pm

**Comment by smwatts** [comment]
screen shot 2018-03-08 at 9 35 57 pm

Not sure what is causing this. Steps to reproduce:
1. Upload courses
2. Apply with one student
3. Disqualify one student

**Comment by amyleblond** [comment]
@smwatts my bad didnt change a var name. Try now

**Review by smwatts — APPROVED** [review]
Awesome job

**Review by j2kan — COMMENTED** [review]
LGTM.

**Pull request merged**
