### PR TITLE
Algorithm development

### PR DESCRIPTION
**Pull request by smwatts**
The algorithm works!! 

To try it yourself please use these test files (last term's example input files)

You will need to save them as .CSV (Git doesn't let me attach CSV file types).
[1_course-info.xlsx](https://github.com/j2kan/ta-works/files/1741409/1_course-info.xlsx)
[2_ranking-info.xlsx](https://github.com/j2kan/ta-works/files/1741410/2_ranking-info.xlsx)

In the command line run the following from the algorithm folder directory:
python2 matchingalgo.py /path-to-course-info/file_name.csv /path-to-ranking-info/file_name.csv > /path-to-output/file_name.csv

The output of our algorithm last year was:
screen shot 2018-02-20 at 1 36 18 pm

The output of our algorithm this year is:
screen shot 2018-02-20 at 2 08 24 pm

***And they match!!***

**Please note: I am not including the courses that did not get matched in this export, we talked about how we may want this to be a separate table so I am leaving it for now until we integrate with the system**

Re: Dr. Smuckers concerns about security, we are currently using the free version of pulp to run this file. We could look into a license that will ensure the problem set is not shared OR we could run the algorithm by course ID and student ID (from our DB) to anonymize it. Depends on the level of security Dr. Smucker wants, but I'm going to look into licensing as part of this ticket. We can ask him in one of our meetings.

(from the Pulp documentation)
screen shot 2018-02-20 at 1 40 05 pm

### CODE REVIEW

**Review by j2kan — DISMISSED** [review]
awesome detail and good job!

Can you add to the readMe as part of end to end testing for this either in a separate PR or this one.

**Comment by amyleblond** [comment]
This is what I ran:
screen shot 2018-02-20 at 3 21 37 pm

This is what I got as output:
screen shot 2018-02-20 at 3 22 14 pm

do I have to install anything?

**Review by amyleblond — DISMISSED** [review]
yayyy it worked :)
screen shot 2018-02-20 at 4 09 40 pm

I had to pip install pulp tho! Will need to happen on the server too!

**Comment by smwatts** [comment]
Really good call-out @amyleblond I forgot to add that you need to pip-install pulp. I'll at that to the requirements.txt and install on server. @j2kan Ill add my testing instructions are part of this PR before merging

**Review by j2kan — APPROVED** [review]
LGTM

**Comment by j2kan** [comment]
We should include the pulp licensing as part of the email for smucker.

**Pull request merged**
