### PR TITLE
centered popups

### PR DESCRIPTION
**Pull request by lauradobson**
Solution as per the following stack over flow answer:

image

By adding Doctype HTML, this removes the spacing in the course table:
image
See the first answer: https://stackoverflow.com/questions/32214152/why-does-my-div-height-100-work-only-when-doctype-is-removed
@j2kan @smwatts @amyleblond let me know what you think

### CODE REVIEW

**Comment by j2kan** [comment]
I left this in the card.
Did you get a chance to see?

https://stackoverflow.com/questions/1839702/how-can-i-position-my-jquery-dialog-to-center

This can help position it directly above the submit button / customize where you want it.

**Comment by lauradobson** [comment]
@j2kan yep, I created a solution for this, but I thought this was a better fix. The answer I posted was in that thread.

**Comment by j2kan** [comment]
Should we add this to the base template? doesn't hurt to have it on all the pages right? No side effects?

**Comment by lauradobson** [comment]
When you use the doctype HTML tag it may change some of the css (look at the stackoverflow link I put in my first comment)
However in the first answer, he indicates that it's best practice to include it and provides a detailed reasoning into it
Let me know what you think! I'll show you the other implementation tomorrow with positioning against elements. Doing the doctype way was a cleaner implementation

**Comment by j2kan** [comment]
screen shot 2018-03-09 at 12 50 30 am

i just read this TLDR.

We should try it on all the browsers and see tomorrow.

**Review by smwatts — APPROVED** [review]
LGTM

**Review by amyleblond — APPROVED** [review]

**Review by j2kan — APPROVED** [review]
lgtm

**Pull request merged**
